context:
  version: "30.0.1"

package:
  name: jest
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/jest/-/jest-${{ version }}.tgz
  sha256: 536b5af0dcf29ca72cf461f847f9298c56310bfbcc69250f5e8056a725c488b7

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - jest --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Delightful JavaScript Testing.
  homepage: https://github.com/jestjs/jest
  repository: https://github.com/jestjs/jest

extra:
  recipe-maintainers:
    - danielnachun
