context:
  version: "30.0.0"

package:
  name: jest
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/jest/-/jest-${{ version }}.tgz
  sha256: e5f07d862ac1e6c81750b0aa36e715bc9cc079343487afbb3cfdca070acddca6

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - jest --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Delightful JavaScript Testing.
  homepage: https://github.com/jestjs/jest
  repository: https://github.com/jestjs/jest

extra:
  recipe-maintainers:
    - danielnachun
