context:
  version: 29.7.0

package:
  name: jest
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/jest/-/jest-${{ version }}.tgz
  sha256: f65aeb744ee062f250b62a1831e03389f39870414e73291eac1dc2b51770fc08

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - jest --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Delightful JavaScript Testing.
  homepage: https://github.com/jestjs/jest
  repository: https://github.com/jestjs/jest

extra:
  recipe-maintainers:
    - danielnachun
